name = "cf-bookkeeping-mvp"
main = "src/worker/index.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "cf-bookkeeping-db"
database_id = "45b142fa-4fcc-42de-9586-54d583f84692"
